// Génère THIRD-PARTY-NOTICES.md : les licences de tout ce qui est livré avec le framework (dépendances de production),
// avec le texte de licence de chacune (les textes identiques sont regroupés). À relancer quand package-lock.json change :
//   npm run licenses          écrit le fichier
//   npm run licenses -- --check   échoue si le fichier n'est plus à jour (utilisé par le test)
import fs from "node:fs";
import path from "node:path";
import { createHash } from "node:crypto";

const root = process.cwd();
const lock = JSON.parse(fs.readFileSync(path.join(root, "package-lock.json"), "utf8"));

export function productionPackages() {
  const out = [];
  for (const [key, v] of Object.entries(lock.packages)) {
    if (!key || v.dev || v.devOptional) continue;
    const name = key.replace(/^.*node_modules\//, "");
    out.push({ key, name, version: v.version, license: v.license ?? "UNKNOWN" });
  }
  return out.sort((a, b) => a.name.localeCompare(b.name) || a.version.localeCompare(b.version));
}

function licenseText(key) {
  const dir = path.join(root, key);
  if (!fs.existsSync(dir)) return null;
  const file = fs.readdirSync(dir).find((f) => /^(licen[cs]e|copying)(\.(md|txt))?$/i.test(f));
  return file ? fs.readFileSync(path.join(dir, file), "utf8").trim() : null;
}

export function render() {
  const pkgs = productionPackages();
  const byLicense = new Map();
  for (const p of pkgs) byLicense.set(p.license, [...(byLicense.get(p.license) ?? []), p]);
  const lines = [
    "# Third-party notices",
    "",
    "Curiosa, developed by [Helldog136](https://helldog136.be), is distributed under the Curiosa License (see `LICENSE`). It includes or depends on the following third-party software, each under its own license.",
    "This file is generated by `npm run licenses` from `package-lock.json` (production dependencies only). Do not edit it by hand.",
    "",
    "## Summary",
    "",
    "| License | Packages |",
    "|---|---|",
    ...[...byLicense].sort((a, b) => b[1].length - a[1].length).map(([l, a]) => `| ${l} | ${a.length} |`),
    "",
    "Notes:",
    "",
    "- Packages under **LGPL-3.0-or-later** (the prebuilt `libvips` binaries used by the image optimizer, `@img/sharp-libvips-*`) are used as separate, dynamically loaded libraries and are not modified. Their license texts and source locations are those of the `@img/sharp-libvips-*` packages.",
    "- `caniuse-lite` (browser compatibility data, used by the build) is licensed CC-BY-4.0: data by Alexis Deveria and contributors, https://github.com/browserslist/caniuse-lite.",
    "- The default font used to render PNG images comes with Next.js (Geist, SIL Open Font License 1.1).",
    "",
    "## Packages",
    "",
  ];
  for (const [license, list] of [...byLicense].sort((a, b) => a[0].localeCompare(b[0]))) {
    lines.push(`### ${license}`, "", list.map((p) => `\`${p.name}@${p.version}\``).join(", "), "");
  }
  // Textes de licence : regroupés quand ils sont identiques (hors ligne de copyright, qui diffère d'un paquet à l'autre).
  const texts = new Map();
  for (const p of pkgs) {
    const t = licenseText(p.key);
    if (!t) continue;
    const id = createHash("sha256").update(t).digest("hex");
    const g = texts.get(id) ?? { text: t, names: [] };
    g.names.push(p.name);
    texts.set(id, g);
  }
  lines.push("## License texts", "");
  for (const { text, names } of [...texts.values()].sort((a, b) => b.names.length - a.names.length || a.names[0].localeCompare(b.names[0]))) {
    lines.push(`<details><summary>${[...new Set(names)].sort().join(", ")}</summary>`, "", "```text", text.replace(/```/g, "'''"), "```", "", "</details>", "");
  }
  return lines.join("\n");
}

if (process.argv[1] && path.resolve(process.argv[1]) === path.resolve(import.meta.filename)) {
  const file = path.join(root, "THIRD-PARTY-NOTICES.md");
  const next = render();
  if (process.argv.includes("--check")) {
    const same = fs.existsSync(file) && fs.readFileSync(file, "utf8") === next;
    if (!same) { console.error("THIRD-PARTY-NOTICES.md n'est plus à jour : lancez `npm run licenses`."); process.exit(1); }
  } else { fs.writeFileSync(file, next); console.log(`THIRD-PARTY-NOTICES.md écrit (${productionPackages().length} paquets).`); }
}
